name: Select specific branch from feature/**

env:
  IMAGE: wedevx/app
  DEPLOYMENT: prod-app-deploy
  CONTAINER_NAME: prod-app
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_KEY }}
            aws-region: eu-west-1

      - uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
            parameterPairs: "/appliction/production/NODE_ENV = NODE_ENV,
            /appliction/production/MODE = MODE
            "
            # The part before equals is the ssm parameterName, and after is the ENV Variable name for the workflow.
            # No limit on number of parameters. You can put new lines and spaces in as desired, they get trimmed out.
            withDecryption: "true" # defaults to true
            
            
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          dockerfile: Dockerfile
          tags: frdevelopergen/app-test:v0.0.0
          build-args: |
            "NODE_ENV=${{ env.NODE_ENV }}"
            "MODE=${{ env.MODE }}"
            
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          mention_groups: 'SAZ94GDB8'
          mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_FAILURE }}
 
