name: Select specific branch from feature/**

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'feature/**')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: print test
        run: env
        
